version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Enabled by default
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional useful linters
    - misspell
    - revive
    - gosec
    - goconst
    - gocyclo
    - bodyclose
    - gocritic

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    enable-all: true
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - bin
    - vendor
