// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"backend/internal/domain"
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// Union type for apply validations result.
type ApplyValidationsResponse interface {
	IsApplyValidationsResponse()
}

// Union type for profile photo deletion result.
type DeleteProfilePhotoResponse interface {
	IsDeleteProfilePhotoResponse()
}

// Union type for education create/update result.
type EducationResponse interface {
	IsEducationResponse()
}

// Union type for experience create/update result.
type ExperienceResponse interface {
	IsExperienceResponse()
}

// Union type for import document results.
type ImportDocumentResultsResponse interface {
	IsImportDocumentResultsResponse()
}

// Union type for process document result.
type ProcessDocumentResponse interface {
	IsProcessDocumentResponse()
}

// Union type for profile header update result.
type ProfileHeaderResponse interface {
	IsProfileHeaderResponse()
}

// Union type for skill create/update result.
type SkillResponse interface {
	IsSkillResponse()
}

// Union type for author image upload result.
type UploadAuthorImageResponse interface {
	IsUploadAuthorImageResponse()
}

// Union type for upload result - either success, validation error, or duplicate detected.
type UploadFileResponse interface {
	IsUploadFileResponse()
}

// Union type for upload for detection result.
type UploadForDetectionResponse interface {
	IsUploadForDetectionResponse()
}

// Union type for profile photo upload result.
type UploadProfilePhotoResponse interface {
	IsUploadProfilePhotoResponse()
}

// Union type for resume upload result - either success, validation error, or duplicate detected.
type UploadResumeResponse interface {
	IsUploadResumeResponse()
}

// Counts of items applied from a reference letter.
type AppliedCount struct {
	// Number of skill validations applied.
	SkillValidations int `json:"skillValidations"`
	// Number of experience validations applied.
	ExperienceValidations int `json:"experienceValidations"`
	// Number of testimonials added.
	Testimonials int `json:"testimonials"`
	// Number of new skills added.
	NewSkills int `json:"newSkills"`
}

// Error returned when applying validations fails.
type ApplyValidationsError struct {
	// Error message describing the failure.
	Message string `json:"message"`
	// The field that caused the error, if applicable.
	Field *string `json:"field,omitempty"`
}

func (ApplyValidationsError) IsApplyValidationsResponse() {}

// Input for applying selected validations from a reference letter.
type ApplyValidationsInput struct {
	// The reference letter ID to apply validations from.
	ReferenceLetterID string `json:"referenceLetterID"`
	// Skill validations to apply.
	SkillValidations []*SkillValidationInput `json:"skillValidations"`
	// Experience validations to apply.
	ExperienceValidations []*ExperienceValidationInput `json:"experienceValidations"`
	// Testimonials to add to the profile.
	Testimonials []*TestimonialInput `json:"testimonials"`
	// New skills discovered in the reference letter to add to the profile.
	NewSkills []*NewSkillInput `json:"newSkills"`
}

// Result of applying reference letter validations.
type ApplyValidationsResult struct {
	// The updated reference letter.
	ReferenceLetter *ReferenceLetter `json:"referenceLetter"`
	// The updated profile.
	Profile *Profile `json:"profile"`
	// Counts of items that were applied.
	AppliedCount *AppliedCount `json:"appliedCount"`
}

func (ApplyValidationsResult) IsApplyValidationsResponse() {}

// A person who provided testimonials for the profile. Authors are deduplicated
// by name and company within a profile.
type Author struct {
	// Unique identifier for the author.
	ID string `json:"id"`
	// Name of the author.
	Name string `json:"name"`
	// Title/position of the author.
	Title *string `json:"title,omitempty"`
	// Company/organization of the author.
	Company *string `json:"company,omitempty"`
	// LinkedIn profile URL of the author.
	LinkedInURL *string `json:"linkedInUrl,omitempty"`
	// Presigned URL for the author's profile image.
	ImageURL *string `json:"imageUrl,omitempty"`
	// When the author record was created.
	CreatedAt time.Time `json:"createdAt"`
	// When the author record was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
	// All testimonials from this author.
	Testimonials []*Testimonial `json:"testimonials"`
}

// Input for creating a new education entry.
type CreateEducationInput struct {
	// Institution name (required).
	Institution string `json:"institution"`
	// Degree or certification (required).
	Degree string `json:"degree"`
	// Field of study.
	Field *string `json:"field,omitempty"`
	// Start date (e.g., 'Jan 2020', '2020').
	StartDate *string `json:"startDate,omitempty"`
	// End date (e.g., 'Dec 2023', 'Present').
	EndDate *string `json:"endDate,omitempty"`
	// Whether currently studying here.
	IsCurrent bool `json:"isCurrent"`
	// Description or achievements.
	Description *string `json:"description,omitempty"`
	// GPA if applicable.
	Gpa *string `json:"gpa,omitempty"`
}

// Input for creating a new work experience.
type CreateExperienceInput struct {
	// Company or organization name (required).
	Company string `json:"company"`
	// Job title or position (required).
	Title string `json:"title"`
	// Location of the job.
	Location *string `json:"location,omitempty"`
	// Start date (e.g., 'Jan 2020', '2020').
	StartDate *string `json:"startDate,omitempty"`
	// End date (e.g., 'Dec 2023', 'Present').
	EndDate *string `json:"endDate,omitempty"`
	// Whether this is the current job.
	IsCurrent bool `json:"isCurrent"`
	// Job description or responsibilities.
	Description *string `json:"description,omitempty"`
	// Key achievements or highlights (bullet points).
	Highlights []string `json:"highlights,omitempty"`
}

// Input for creating a new skill.
type CreateSkillInput struct {
	// Skill name (required).
	Name string `json:"name"`
	// Skill category (required).
	Category domain.SkillCategory `json:"category"`
}

// Result of deleting a profile photo.
type DeleteProfilePhotoResult struct {
	// Whether the deletion was successful.
	Success bool `json:"success"`
}

func (DeleteProfilePhotoResult) IsDeleteProfilePhotoResponse() {}

// Result of a delete operation.
type DeleteResult struct {
	// Whether the deletion was successful.
	Success bool `json:"success"`
	// ID of the deleted item.
	DeletedID string `json:"deletedId"`
}

// Result of lightweight document content detection.
// Used to quickly classify a document before running full extraction.
type DocumentDetectionResult struct {
	// Whether the document contains career information (resume/CV content).
	HasCareerInfo bool `json:"hasCareerInfo"`
	// Whether the document contains testimonial/recommendation content.
	HasTestimonial bool `json:"hasTestimonial"`
	// Name of the testimonial author (person who wrote the recommendation), if detected.
	TestimonialAuthor *string `json:"testimonialAuthor,omitempty"`
	// Confidence in the detection (0.0 to 1.0).
	Confidence float64 `json:"confidence"`
	// Brief summary of what was found in the document.
	Summary string `json:"summary"`
	// Hint about the document type.
	DocumentTypeHint DocumentTypeHint `json:"documentTypeHint"`
	// ID of the stored file for subsequent processing.
	FileID string `json:"fileId"`
}

// Status of a document detection job.
// Poll this query to track detection progress after uploadForDetection.
type DocumentDetectionStatus struct {
	// The file ID being detected.
	FileID string `json:"fileId"`
	// Current detection status.
	Status DetectionStatus `json:"status"`
	// Detection results, available when status is COMPLETED.
	Detection *DocumentDetectionResult `json:"detection,omitempty"`
	// Error message, set when status is FAILED.
	Error *string `json:"error,omitempty"`
}

// Input for reporting feedback about document detection or extraction.
type DocumentFeedbackInput struct {
	// ID of the file the feedback relates to.
	FileID string `json:"fileId"`
	// The type of feedback being reported.
	FeedbackType DocumentFeedbackType `json:"feedbackType"`
	// Free-text message describing the issue.
	Message string `json:"message"`
}

// Result of reporting document feedback.
type DocumentFeedbackResult struct {
	// Whether the feedback was recorded successfully.
	Success bool `json:"success"`
}

// Aggregated processing status across resume and reference letter extraction.
type DocumentProcessingStatus struct {
	// Resume processing status (null if resume extraction was not requested).
	Resume *Resume `json:"resume,omitempty"`
	// Reference letter processing status (null if letter extraction was not requested).
	ReferenceLetter *ReferenceLetter `json:"referenceLetter,omitempty"`
	// Overall status: true when all requested extractions are complete (COMPLETED or FAILED).
	AllComplete bool `json:"allComplete"`
}

// Result when a duplicate file is detected during upload.
type DuplicateFileDetected struct {
	// The existing file that matches the uploaded content.
	ExistingFile *File `json:"existingFile"`
	// The existing resume created from this file (if uploading a resume).
	ExistingResume *Resume `json:"existingResume,omitempty"`
	// The existing reference letter created from this file (if uploading a reference letter).
	ExistingReferenceLetter *ReferenceLetter `json:"existingReferenceLetter,omitempty"`
	// Message describing the duplicate detection.
	Message string `json:"message"`
}

func (DuplicateFileDetected) IsUploadFileResponse() {}

func (DuplicateFileDetected) IsUploadResumeResponse() {}

// Result of a successful education operation.
type EducationResult struct {
	// The created or updated education entry.
	Education *ProfileEducation `json:"education"`
}

func (EducationResult) IsEducationResponse() {}

// Error returned when education validation fails.
type EducationValidationError struct {
	// Error message describing the validation failure.
	Message string `json:"message"`
	// The field that failed validation.
	Field *string `json:"field,omitempty"`
}

func (EducationValidationError) IsEducationResponse() {}

// Result of a successful experience operation.
type ExperienceResult struct {
	// The created or updated experience.
	Experience *ProfileExperience `json:"experience"`
}

func (ExperienceResult) IsExperienceResponse() {}

// A validation record linking an experience to a reference letter.
type ExperienceValidation struct {
	// Unique identifier for the validation.
	ID string `json:"id"`
	// The experience being validated.
	Experience *ProfileExperience `json:"experience"`
	// The reference letter providing the validation.
	ReferenceLetter *ReferenceLetter `json:"referenceLetter"`
	// Quote snippet from the reference letter supporting this experience.
	QuoteSnippet *string `json:"quoteSnippet,omitempty"`
	// When the validation was created.
	CreatedAt time.Time `json:"createdAt"`
}

// Error returned when experience validation fails.
type ExperienceValidationError struct {
	// Error message describing the validation failure.
	Message string `json:"message"`
	// The field that failed validation.
	Field *string `json:"field,omitempty"`
}

func (ExperienceValidationError) IsExperienceResponse() {}

// Input for applying an experience validation from a reference letter.
type ExperienceValidationInput struct {
	// The profile experience ID to validate.
	ProfileExperienceID string `json:"profileExperienceID"`
	// Quote snippet from the reference letter supporting this experience.
	QuoteSnippet string `json:"quoteSnippet"`
}

// An education entry extracted from a resume.
type ExtractedEducation struct {
	// Institution name.
	Institution string `json:"institution"`
	// Degree earned.
	Degree *string `json:"degree,omitempty"`
	// Field of study.
	Field *string `json:"field,omitempty"`
	// Start date.
	StartDate *string `json:"startDate,omitempty"`
	// End date.
	EndDate *string `json:"endDate,omitempty"`
	// Grade point average.
	Gpa *string `json:"gpa,omitempty"`
	// Achievements or honors.
	Achievements *string `json:"achievements,omitempty"`
}

// A work experience entry extracted from a resume.
type ExtractedWorkExperience struct {
	// Company or organization name.
	Company string `json:"company"`
	// Job title or role.
	Title string `json:"title"`
	// Location of the role.
	Location *string `json:"location,omitempty"`
	// Start date (YYYY-MM format).
	StartDate *string `json:"startDate,omitempty"`
	// End date (YYYY-MM format), null if current.
	EndDate *string `json:"endDate,omitempty"`
	// Whether this is the current position.
	IsCurrent bool `json:"isCurrent"`
	// Role description or achievements.
	Description *string `json:"description,omitempty"`
}

// An uploaded file stored in object storage.
type File struct {
	ID          string `json:"id"`
	Filename    string `json:"filename"`
	ContentType string `json:"contentType"`
	SizeBytes   int    `json:"sizeBytes"`
	StorageKey  string `json:"storageKey"`
	// SHA-256 hash of the file content for duplicate detection.
	ContentHash *string `json:"contentHash,omitempty"`
	// Presigned URL for downloading the file. Expires after a short time.
	URL       string    `json:"url"`
	CreatedAt time.Time `json:"createdAt"`
	User      *User     `json:"user"`
}

// Error returned when file validation fails.
type FileValidationError struct {
	// Error message describing the validation failure.
	Message string `json:"message"`
	// The field that failed validation (e.g., 'contentType', 'size').
	Field string `json:"field"`
}

func (FileValidationError) IsUploadForDetectionResponse() {}

func (FileValidationError) IsUploadProfilePhotoResponse() {}

func (FileValidationError) IsUploadAuthorImageResponse() {}

func (FileValidationError) IsUploadFileResponse() {}

func (FileValidationError) IsUploadResumeResponse() {}

// Error returned when import document results validation fails.
type ImportDocumentResultsError struct {
	// Error message describing the failure.
	Message string `json:"message"`
	// The field that caused the error.
	Field *string `json:"field,omitempty"`
}

func (ImportDocumentResultsError) IsImportDocumentResultsResponse() {}

// Input for importing extracted document results into profile tables.
type ImportDocumentResultsInput struct {
	// Resume ID to materialize into profile (null to skip).
	ResumeID *string `json:"resumeId,omitempty"`
	// Reference letter ID whose validations should be applied (null to skip).
	ReferenceLetterID *string `json:"referenceLetterID,omitempty"`
	// Indices of experiences to import. Null = import all.
	SelectedExperienceIndices []int `json:"selectedExperienceIndices,omitempty"`
	// Indices of education entries to import. Null = import all.
	SelectedEducationIndices []int `json:"selectedEducationIndices,omitempty"`
	// Skill names to import. Null = import all.
	SelectedSkills []string `json:"selectedSkills,omitempty"`
	// Indices of testimonials to import. Null = import all.
	SelectedTestimonialIndices []int `json:"selectedTestimonialIndices,omitempty"`
	// Discovered skills to import from reference letter with per-skill category. Null = import all.
	SelectedDiscoveredSkills []*SelectedDiscoveredSkillInput `json:"selectedDiscoveredSkills,omitempty"`
}

// Result of importing document results into profile tables.
type ImportDocumentResultsResult struct {
	// The updated profile after materialization.
	Profile *Profile `json:"profile"`
	// Counts of items that were imported.
	ImportedCount *ImportedCount `json:"importedCount"`
}

func (ImportDocumentResultsResult) IsImportDocumentResultsResponse() {}

// Counts of items imported into the profile.
type ImportedCount struct {
	// Number of work experiences materialized.
	Experiences int `json:"experiences"`
	// Number of education entries materialized.
	Educations int `json:"educations"`
	// Number of skills materialized.
	Skills int `json:"skills"`
	// Number of testimonials materialized from reference letters.
	Testimonials int `json:"testimonials"`
}

type Mutation struct {
}

// Input for adding a new skill discovered in the reference letter.
type NewSkillInput struct {
	// The skill name.
	Name string `json:"name"`
	// The skill category.
	Category domain.SkillCategory `json:"category"`
	// Quote context from the reference letter mentioning this skill.
	QuoteContext *string `json:"quoteContext,omitempty"`
}

// Error returned when process document validation fails.
type ProcessDocumentError struct {
	// Error message describing the validation failure.
	Message string `json:"message"`
	// The field that failed validation.
	Field *string `json:"field,omitempty"`
}

func (ProcessDocumentError) IsProcessDocumentResponse() {}

// Input for processing a previously uploaded document.
// The fileId must reference a file previously stored via uploadForDetection.
type ProcessDocumentInput struct {
	// ID of the file already stored via uploadForDetection.
	FileID string `json:"fileId"`
	// Whether to extract career/resume information from the document.
	ExtractCareerInfo bool `json:"extractCareerInfo"`
	// Whether to extract testimonial/reference letter content from the document.
	ExtractTestimonial bool `json:"extractTestimonial"`
}

// IDs of the entities created for tracking extraction progress.
type ProcessDocumentResult struct {
	// Resume ID created for career info extraction (null if not requested).
	ResumeID *string `json:"resumeId,omitempty"`
	// Reference letter ID created for testimonial extraction (null if not requested).
	ReferenceLetterID *string `json:"referenceLetterID,omitempty"`
}

func (ProcessDocumentResult) IsProcessDocumentResponse() {}

// A user's profile containing manually editable data.
type Profile struct {
	ID string `json:"id"`
	// The user who owns this profile.
	User *User `json:"user"`
	// User-edited name (overrides resume extraction if set).
	Name *string `json:"name,omitempty"`
	// User-edited email (overrides resume extraction if set).
	Email *string `json:"email,omitempty"`
	// User-edited phone (overrides resume extraction if set).
	Phone *string `json:"phone,omitempty"`
	// User-edited location (overrides resume extraction if set).
	Location *string `json:"location,omitempty"`
	// User-edited professional summary (overrides resume extraction if set).
	Summary *string `json:"summary,omitempty"`
	// URL to the user's profile photo (presigned URL for direct access).
	ProfilePhotoURL *string `json:"profilePhotoUrl,omitempty"`
	// Work experience entries.
	Experiences []*ProfileExperience `json:"experiences"`
	// Education entries.
	Educations []*ProfileEducation `json:"educations"`
	// Skill entries.
	Skills    []*ProfileSkill `json:"skills"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

// An education entry in a user's profile.
type ProfileEducation struct {
	// Unique identifier for the education entry.
	ID string `json:"id"`
	// Institution name.
	Institution string `json:"institution"`
	// Degree or certification.
	Degree string `json:"degree"`
	// Field of study.
	Field *string `json:"field,omitempty"`
	// Start date (e.g., 'Jan 2020', '2020').
	StartDate *string `json:"startDate,omitempty"`
	// End date (e.g., 'Dec 2023', 'Present').
	EndDate *string `json:"endDate,omitempty"`
	// Whether currently studying here.
	IsCurrent bool `json:"isCurrent"`
	// Description or achievements.
	Description *string `json:"description,omitempty"`
	// GPA if applicable.
	Gpa *string `json:"gpa,omitempty"`
	// Display order for sorting.
	DisplayOrder int `json:"displayOrder"`
	// Source of this education entry.
	Source    ExperienceSource `json:"source"`
	CreatedAt time.Time        `json:"createdAt"`
	UpdatedAt time.Time        `json:"updatedAt"`
}

// A work experience entry in a user's profile.
type ProfileExperience struct {
	// Unique identifier for the experience.
	ID string `json:"id"`
	// Company or organization name.
	Company string `json:"company"`
	// Job title or position.
	Title string `json:"title"`
	// Location of the job.
	Location *string `json:"location,omitempty"`
	// Start date (e.g., 'Jan 2020', '2020').
	StartDate *string `json:"startDate,omitempty"`
	// End date (e.g., 'Dec 2023', 'Present').
	EndDate *string `json:"endDate,omitempty"`
	// Whether this is the current job.
	IsCurrent bool `json:"isCurrent"`
	// Job description or responsibilities.
	Description *string `json:"description,omitempty"`
	// Key achievements or highlights (bullet points).
	Highlights []string `json:"highlights"`
	// Display order for sorting.
	DisplayOrder int `json:"displayOrder"`
	// Source of this experience entry.
	Source ExperienceSource `json:"source"`
	// Number of reference letters validating this experience.
	ValidationCount int       `json:"validationCount"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

// Result of a successful profile header update.
type ProfileHeaderResult struct {
	// The updated profile.
	Profile *Profile `json:"profile"`
}

func (ProfileHeaderResult) IsProfileHeaderResponse() {}

// Error returned when profile header validation fails.
type ProfileHeaderValidationError struct {
	// Error message describing the validation failure.
	Message string `json:"message"`
	// The field that failed validation.
	Field *string `json:"field,omitempty"`
}

func (ProfileHeaderValidationError) IsProfileHeaderResponse() {}

func (ProfileHeaderValidationError) IsDeleteProfilePhotoResponse() {}

// A skill entry in a user's profile.
type ProfileSkill struct {
	// Unique identifier for the skill.
	ID string `json:"id"`
	// Skill name as displayed.
	Name string `json:"name"`
	// Normalized skill name for deduplication.
	NormalizedName string `json:"normalizedName"`
	// Skill category.
	Category domain.SkillCategory `json:"category"`
	// Display order for sorting.
	DisplayOrder int `json:"displayOrder"`
	// Source of this skill entry.
	Source ExperienceSource `json:"source"`
	// Number of reference letters validating this skill.
	ValidationCount int `json:"validationCount"`
	// The reference letter this skill was discovered from (if source is reference letter).
	SourceReferenceLetter *ReferenceLetter `json:"sourceReferenceLetter,omitempty"`
	CreatedAt             time.Time        `json:"createdAt"`
	UpdatedAt             time.Time        `json:"updatedAt"`
}

type Query struct {
}

// A reference letter with extracted data.
type ReferenceLetter struct {
	ID           string     `json:"id"`
	Title        *string    `json:"title,omitempty"`
	AuthorName   *string    `json:"authorName,omitempty"`
	AuthorTitle  *string    `json:"authorTitle,omitempty"`
	Organization *string    `json:"organization,omitempty"`
	DateWritten  *time.Time `json:"dateWritten,omitempty"`
	RawText      *string    `json:"rawText,omitempty"`
	// Structured data extracted from the letter by LLM processing.
	ExtractedData *ExtractedLetterData  `json:"extractedData,omitempty"`
	Status        ReferenceLetterStatus `json:"status"`
	CreatedAt     time.Time             `json:"createdAt"`
	UpdatedAt     time.Time             `json:"updatedAt"`
	User          *User                 `json:"user"`
	File          *File                 `json:"file,omitempty"`
}

// An uploaded resume with extracted profile data.
type Resume struct {
	ID string `json:"id"`
	// Processing status of the resume.
	Status ResumeStatus `json:"status"`
	// Structured data extracted from the resume by LLM processing.
	ExtractedData *ResumeExtractedData `json:"extractedData,omitempty"`
	// Error message if processing failed.
	ErrorMessage *string   `json:"errorMessage,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
	User         *User     `json:"user"`
	File         *File     `json:"file"`
}

// Structured data extracted from a resume.
// Education and work experience are materialized into profile tables
// and exposed via ProfileEducation/ProfileExperience types.
type ResumeExtractedData struct {
	// Full name of the candidate.
	Name string `json:"name"`
	// Email address.
	Email *string `json:"email,omitempty"`
	// Phone number.
	Phone *string `json:"phone,omitempty"`
	// Location (city, state, country).
	Location *string `json:"location,omitempty"`
	// Professional summary or objective.
	Summary *string `json:"summary,omitempty"`
	// Work experience entries.
	Experiences []*ExtractedWorkExperience `json:"experiences"`
	// Education entries.
	Educations []*ExtractedEducation `json:"educations"`
	// Skill names.
	Skills []string `json:"skills"`
	// When the extraction was performed.
	ExtractedAt time.Time `json:"extractedAt"`
	// Overall confidence score (0.0 to 1.0).
	Confidence float64 `json:"confidence"`
}

// Input for a discovered skill selected for import, carrying both name and category.
type SelectedDiscoveredSkillInput struct {
	// The skill name.
	Name string `json:"name"`
	// The skill category (user may override the LLM-assigned category).
	Category domain.SkillCategory `json:"category"`
}

// Result of a successful skill operation.
type SkillResult struct {
	// The created or updated skill.
	Skill *ProfileSkill `json:"skill"`
}

func (SkillResult) IsSkillResponse() {}

// A validation record linking a skill to a reference letter.
type SkillValidation struct {
	// Unique identifier for the validation.
	ID string `json:"id"`
	// The skill being validated.
	Skill *ProfileSkill `json:"skill"`
	// The reference letter providing the validation.
	ReferenceLetter *ReferenceLetter `json:"referenceLetter"`
	// The specific testimonial that validates this skill (if applicable).
	Testimonial *Testimonial `json:"testimonial,omitempty"`
	// Quote snippet from the reference letter supporting this skill.
	QuoteSnippet *string `json:"quoteSnippet,omitempty"`
	// When the validation was created.
	CreatedAt time.Time `json:"createdAt"`
}

// Error returned when skill validation fails.
type SkillValidationError struct {
	// Error message describing the validation failure.
	Message string `json:"message"`
	// The field that failed validation.
	Field *string `json:"field,omitempty"`
}

func (SkillValidationError) IsSkillResponse() {}

// Input for applying a skill validation from a reference letter.
type SkillValidationInput struct {
	// The profile skill ID to validate.
	ProfileSkillID string `json:"profileSkillID"`
	// Quote snippet from the reference letter supporting this skill.
	QuoteSnippet string `json:"quoteSnippet"`
}

// A testimonial quote from a reference letter displayed on the profile.
type Testimonial struct {
	// Unique identifier for the testimonial.
	ID string `json:"id"`
	// The full quote text.
	Quote string `json:"quote"`
	// The author who provided this testimonial.
	Author *Author `json:"author,omitempty"`
	// Name of the person who provided the testimonial. (Deprecated: use author.name)
	AuthorName string `json:"authorName"`
	// Title/position of the author. (Deprecated: use author.title)
	AuthorTitle *string `json:"authorTitle,omitempty"`
	// Company/organization of the author. (Deprecated: use author.company)
	AuthorCompany *string `json:"authorCompany,omitempty"`
	// Relationship between the author and the profile owner.
	Relationship TestimonialRelationship `json:"relationship"`
	// The reference letter this testimonial was extracted from.
	ReferenceLetter *ReferenceLetter `json:"referenceLetter,omitempty"`
	// When the testimonial was created.
	CreatedAt time.Time `json:"createdAt"`
	// Skills validated by this testimonial's reference letter.
	ValidatedSkills []*ProfileSkill `json:"validatedSkills"`
}

// Input for creating a testimonial from a reference letter.
type TestimonialInput struct {
	// The full quote text for the testimonial.
	Quote string `json:"quote"`
	// Skills mentioned in this testimonial.
	SkillsMentioned []string `json:"skillsMentioned"`
}

// Input for updating an author's information.
type UpdateAuthorInput struct {
	// Updated name of the author.
	Name *string `json:"name,omitempty"`
	// Updated title/position of the author.
	Title *string `json:"title,omitempty"`
	// Updated company/organization of the author.
	Company *string `json:"company,omitempty"`
	// Updated LinkedIn profile URL of the author.
	LinkedInURL *string `json:"linkedInUrl,omitempty"`
	// ID of the uploaded image file for the author's profile picture.
	ImageID *string `json:"imageId,omitempty"`
}

// Input for updating an existing education entry.
type UpdateEducationInput struct {
	// Institution name.
	Institution *string `json:"institution,omitempty"`
	// Degree or certification.
	Degree *string `json:"degree,omitempty"`
	// Field of study.
	Field *string `json:"field,omitempty"`
	// Start date (e.g., 'Jan 2020', '2020').
	StartDate *string `json:"startDate,omitempty"`
	// End date (e.g., 'Dec 2023', 'Present').
	EndDate *string `json:"endDate,omitempty"`
	// Whether currently studying here.
	IsCurrent *bool `json:"isCurrent,omitempty"`
	// Description or achievements.
	Description *string `json:"description,omitempty"`
	// GPA if applicable.
	Gpa *string `json:"gpa,omitempty"`
}

// Input for updating an existing work experience.
type UpdateExperienceInput struct {
	// Company or organization name.
	Company *string `json:"company,omitempty"`
	// Job title or position.
	Title *string `json:"title,omitempty"`
	// Location of the job.
	Location *string `json:"location,omitempty"`
	// Start date (e.g., 'Jan 2020', '2020').
	StartDate *string `json:"startDate,omitempty"`
	// End date (e.g., 'Dec 2023', 'Present').
	EndDate *string `json:"endDate,omitempty"`
	// Whether this is the current job.
	IsCurrent *bool `json:"isCurrent,omitempty"`
	// Job description or responsibilities.
	Description *string `json:"description,omitempty"`
	// Key achievements or highlights (bullet points).
	Highlights []string `json:"highlights,omitempty"`
}

// Input for updating profile header fields.
type UpdateProfileHeaderInput struct {
	// Name to display.
	Name *string `json:"name,omitempty"`
	// Email address.
	Email *string `json:"email,omitempty"`
	// Phone number.
	Phone *string `json:"phone,omitempty"`
	// Location (city, state, country).
	Location *string `json:"location,omitempty"`
	// Professional summary.
	Summary *string `json:"summary,omitempty"`
}

// Input for updating an existing skill.
type UpdateSkillInput struct {
	// Skill name.
	Name *string `json:"name,omitempty"`
	// Skill category.
	Category *domain.SkillCategory `json:"category,omitempty"`
}

// Result of a successful author image upload.
type UploadAuthorImageResult struct {
	// The uploaded file metadata.
	File *File `json:"file"`
	// The updated author with image URL.
	Author *Author `json:"author"`
}

func (UploadAuthorImageResult) IsUploadAuthorImageResponse() {}

// Result of a file upload operation.
type UploadFileResult struct {
	// The uploaded file metadata.
	File *File `json:"file"`
	// The reference letter created for processing.
	ReferenceLetter *ReferenceLetter `json:"referenceLetter"`
}

func (UploadFileResult) IsUploadFileResponse() {}

// Result of a successful document upload for detection.
// Returns the file ID for polling detection status.
type UploadForDetectionResult struct {
	// The ID of the uploaded file.
	FileID string `json:"fileId"`
}

func (UploadForDetectionResult) IsUploadForDetectionResponse() {}

// Result of a successful profile photo upload.
type UploadProfilePhotoResult struct {
	// The updated profile with photo URL.
	Profile *Profile `json:"profile"`
}

func (UploadProfilePhotoResult) IsUploadProfilePhotoResponse() {}

// Result of a resume upload operation.
type UploadResumeResult struct {
	// The uploaded file metadata.
	File *File `json:"file"`
	// The resume created for processing.
	Resume *Resume `json:"resume"`
}

func (UploadResumeResult) IsUploadResumeResponse() {}

// A user account in the system.
type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Name      *string   `json:"name,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// Status of asynchronous document detection.
type DetectionStatus string

const (
	DetectionStatusPending    DetectionStatus = "PENDING"
	DetectionStatusProcessing DetectionStatus = "PROCESSING"
	DetectionStatusCompleted  DetectionStatus = "COMPLETED"
	DetectionStatusFailed     DetectionStatus = "FAILED"
)

var AllDetectionStatus = []DetectionStatus{
	DetectionStatusPending,
	DetectionStatusProcessing,
	DetectionStatusCompleted,
	DetectionStatusFailed,
}

func (e DetectionStatus) IsValid() bool {
	switch e {
	case DetectionStatusPending, DetectionStatusProcessing, DetectionStatusCompleted, DetectionStatusFailed:
		return true
	}
	return false
}

func (e DetectionStatus) String() string {
	return string(e)
}

func (e *DetectionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DetectionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DetectionStatus", str)
	}
	return nil
}

func (e DetectionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DetectionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DetectionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The type of feedback being reported about document processing.
type DocumentFeedbackType string

const (
	// Feedback about incorrect document type detection.
	DocumentFeedbackTypeDetectionCorrection DocumentFeedbackType = "DETECTION_CORRECTION"
	// Feedback about extraction quality issues.
	DocumentFeedbackTypeExtractionQuality DocumentFeedbackType = "EXTRACTION_QUALITY"
)

var AllDocumentFeedbackType = []DocumentFeedbackType{
	DocumentFeedbackTypeDetectionCorrection,
	DocumentFeedbackTypeExtractionQuality,
}

func (e DocumentFeedbackType) IsValid() bool {
	switch e {
	case DocumentFeedbackTypeDetectionCorrection, DocumentFeedbackTypeExtractionQuality:
		return true
	}
	return false
}

func (e DocumentFeedbackType) String() string {
	return string(e)
}

func (e *DocumentFeedbackType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DocumentFeedbackType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DocumentFeedbackType", str)
	}
	return nil
}

func (e DocumentFeedbackType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DocumentFeedbackType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DocumentFeedbackType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Hint about the document type from lightweight detection.
type DocumentTypeHint string

const (
	DocumentTypeHintResume          DocumentTypeHint = "RESUME"
	DocumentTypeHintReferenceLetter DocumentTypeHint = "REFERENCE_LETTER"
	DocumentTypeHintHybrid          DocumentTypeHint = "HYBRID"
	DocumentTypeHintUnknown         DocumentTypeHint = "UNKNOWN"
)

var AllDocumentTypeHint = []DocumentTypeHint{
	DocumentTypeHintResume,
	DocumentTypeHintReferenceLetter,
	DocumentTypeHintHybrid,
	DocumentTypeHintUnknown,
}

func (e DocumentTypeHint) IsValid() bool {
	switch e {
	case DocumentTypeHintResume, DocumentTypeHintReferenceLetter, DocumentTypeHintHybrid, DocumentTypeHintUnknown:
		return true
	}
	return false
}

func (e DocumentTypeHint) String() string {
	return string(e)
}

func (e *DocumentTypeHint) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DocumentTypeHint(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DocumentTypeHint", str)
	}
	return nil
}

func (e DocumentTypeHint) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DocumentTypeHint) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DocumentTypeHint) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Source of a profile experience entry.
type ExperienceSource string

const (
	// Manually entered by user.
	ExperienceSourceManual ExperienceSource = "MANUAL"
	// Extracted from an uploaded resume.
	ExperienceSourceResumeExtracted ExperienceSource = "RESUME_EXTRACTED"
	// Discovered in a reference letter.
	ExperienceSourceLetterDiscovered ExperienceSource = "LETTER_DISCOVERED"
)

var AllExperienceSource = []ExperienceSource{
	ExperienceSourceManual,
	ExperienceSourceResumeExtracted,
	ExperienceSourceLetterDiscovered,
}

func (e ExperienceSource) IsValid() bool {
	switch e {
	case ExperienceSourceManual, ExperienceSourceResumeExtracted, ExperienceSourceLetterDiscovered:
		return true
	}
	return false
}

func (e ExperienceSource) String() string {
	return string(e)
}

func (e *ExperienceSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExperienceSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExperienceSource", str)
	}
	return nil
}

func (e ExperienceSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExperienceSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExperienceSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Processing status of a reference letter.
type ReferenceLetterStatus string

const (
	ReferenceLetterStatusPending    ReferenceLetterStatus = "PENDING"
	ReferenceLetterStatusProcessing ReferenceLetterStatus = "PROCESSING"
	ReferenceLetterStatusCompleted  ReferenceLetterStatus = "COMPLETED"
	ReferenceLetterStatusFailed     ReferenceLetterStatus = "FAILED"
	ReferenceLetterStatusApplied    ReferenceLetterStatus = "APPLIED"
)

var AllReferenceLetterStatus = []ReferenceLetterStatus{
	ReferenceLetterStatusPending,
	ReferenceLetterStatusProcessing,
	ReferenceLetterStatusCompleted,
	ReferenceLetterStatusFailed,
	ReferenceLetterStatusApplied,
}

func (e ReferenceLetterStatus) IsValid() bool {
	switch e {
	case ReferenceLetterStatusPending, ReferenceLetterStatusProcessing, ReferenceLetterStatusCompleted, ReferenceLetterStatusFailed, ReferenceLetterStatusApplied:
		return true
	}
	return false
}

func (e ReferenceLetterStatus) String() string {
	return string(e)
}

func (e *ReferenceLetterStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReferenceLetterStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReferenceLetterStatus", str)
	}
	return nil
}

func (e ReferenceLetterStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReferenceLetterStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReferenceLetterStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Processing status of a resume.
type ResumeStatus string

const (
	ResumeStatusPending    ResumeStatus = "PENDING"
	ResumeStatusProcessing ResumeStatus = "PROCESSING"
	ResumeStatusCompleted  ResumeStatus = "COMPLETED"
	ResumeStatusFailed     ResumeStatus = "FAILED"
)

var AllResumeStatus = []ResumeStatus{
	ResumeStatusPending,
	ResumeStatusProcessing,
	ResumeStatusCompleted,
	ResumeStatusFailed,
}

func (e ResumeStatus) IsValid() bool {
	switch e {
	case ResumeStatusPending, ResumeStatusProcessing, ResumeStatusCompleted, ResumeStatusFailed:
		return true
	}
	return false
}

func (e ResumeStatus) String() string {
	return string(e)
}

func (e *ResumeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ResumeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ResumeStatus", str)
	}
	return nil
}

func (e ResumeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ResumeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ResumeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Relationship type between testimonial author and the profile owner.
type TestimonialRelationship string

const (
	TestimonialRelationshipManager      TestimonialRelationship = "MANAGER"
	TestimonialRelationshipPeer         TestimonialRelationship = "PEER"
	TestimonialRelationshipDirectReport TestimonialRelationship = "DIRECT_REPORT"
	TestimonialRelationshipClient       TestimonialRelationship = "CLIENT"
	TestimonialRelationshipOther        TestimonialRelationship = "OTHER"
)

var AllTestimonialRelationship = []TestimonialRelationship{
	TestimonialRelationshipManager,
	TestimonialRelationshipPeer,
	TestimonialRelationshipDirectReport,
	TestimonialRelationshipClient,
	TestimonialRelationshipOther,
}

func (e TestimonialRelationship) IsValid() bool {
	switch e {
	case TestimonialRelationshipManager, TestimonialRelationshipPeer, TestimonialRelationshipDirectReport, TestimonialRelationshipClient, TestimonialRelationshipOther:
		return true
	}
	return false
}

func (e TestimonialRelationship) String() string {
	return string(e)
}

func (e *TestimonialRelationship) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TestimonialRelationship(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TestimonialRelationship", str)
	}
	return nil
}

func (e TestimonialRelationship) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TestimonialRelationship) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TestimonialRelationship) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
