// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"backend/internal/domain"
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// Union type for education create/update result.
type EducationResponse interface {
	IsEducationResponse()
}

// Union type for experience create/update result.
type ExperienceResponse interface {
	IsExperienceResponse()
}

// Union type for skill create/update result.
type SkillResponse interface {
	IsSkillResponse()
}

// Union type for upload result - either success or validation error.
type UploadFileResponse interface {
	IsUploadFileResponse()
}

// Union type for resume upload result - either success or validation error.
type UploadResumeResponse interface {
	IsUploadResumeResponse()
}

// Input for creating a new education entry.
type CreateEducationInput struct {
	// Institution name (required).
	Institution string `json:"institution"`
	// Degree or certification (required).
	Degree string `json:"degree"`
	// Field of study.
	Field *string `json:"field,omitempty"`
	// Start date (e.g., 'Jan 2020', '2020').
	StartDate *string `json:"startDate,omitempty"`
	// End date (e.g., 'Dec 2023', 'Present').
	EndDate *string `json:"endDate,omitempty"`
	// Whether currently studying here.
	IsCurrent bool `json:"isCurrent"`
	// Description or achievements.
	Description *string `json:"description,omitempty"`
	// GPA if applicable.
	Gpa *string `json:"gpa,omitempty"`
}

// Input for creating a new work experience.
type CreateExperienceInput struct {
	// Company or organization name (required).
	Company string `json:"company"`
	// Job title or position (required).
	Title string `json:"title"`
	// Location of the job.
	Location *string `json:"location,omitempty"`
	// Start date (e.g., 'Jan 2020', '2020').
	StartDate *string `json:"startDate,omitempty"`
	// End date (e.g., 'Dec 2023', 'Present').
	EndDate *string `json:"endDate,omitempty"`
	// Whether this is the current job.
	IsCurrent bool `json:"isCurrent"`
	// Job description or responsibilities.
	Description *string `json:"description,omitempty"`
	// Key achievements or highlights (bullet points).
	Highlights []string `json:"highlights,omitempty"`
}

// Input for creating a new skill.
type CreateSkillInput struct {
	// Skill name (required).
	Name string `json:"name"`
	// Skill category (required).
	Category domain.SkillCategory `json:"category"`
}

// Result of a delete operation.
type DeleteResult struct {
	// Whether the deletion was successful.
	Success bool `json:"success"`
	// ID of the deleted item.
	DeletedID string `json:"deletedId"`
}

// Result of a successful education operation.
type EducationResult struct {
	// The created or updated education entry.
	Education *ProfileEducation `json:"education"`
}

func (EducationResult) IsEducationResponse() {}

// Error returned when education validation fails.
type EducationValidationError struct {
	// Error message describing the validation failure.
	Message string `json:"message"`
	// The field that failed validation.
	Field *string `json:"field,omitempty"`
}

func (EducationValidationError) IsEducationResponse() {}

// Result of a successful experience operation.
type ExperienceResult struct {
	// The created or updated experience.
	Experience *ProfileExperience `json:"experience"`
}

func (ExperienceResult) IsExperienceResponse() {}

// Error returned when experience validation fails.
type ExperienceValidationError struct {
	// Error message describing the validation failure.
	Message string `json:"message"`
	// The field that failed validation.
	Field *string `json:"field,omitempty"`
}

func (ExperienceValidationError) IsExperienceResponse() {}

// An uploaded file stored in object storage.
type File struct {
	ID          string    `json:"id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"contentType"`
	SizeBytes   int       `json:"sizeBytes"`
	StorageKey  string    `json:"storageKey"`
	CreatedAt   time.Time `json:"createdAt"`
	User        *User     `json:"user"`
}

// Error returned when file validation fails.
type FileValidationError struct {
	// Error message describing the validation failure.
	Message string `json:"message"`
	// The field that failed validation (e.g., 'contentType', 'size').
	Field string `json:"field"`
}

func (FileValidationError) IsUploadFileResponse() {}

func (FileValidationError) IsUploadResumeResponse() {}

type Mutation struct {
}

// A user's profile containing manually editable data.
type Profile struct {
	ID string `json:"id"`
	// The user who owns this profile.
	User *User `json:"user"`
	// Work experience entries.
	Experiences []*ProfileExperience `json:"experiences"`
	// Education entries.
	Educations []*ProfileEducation `json:"educations"`
	// Skill entries.
	Skills    []*ProfileSkill `json:"skills"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

// An education entry in a user's profile.
type ProfileEducation struct {
	// Unique identifier for the education entry.
	ID string `json:"id"`
	// Institution name.
	Institution string `json:"institution"`
	// Degree or certification.
	Degree string `json:"degree"`
	// Field of study.
	Field *string `json:"field,omitempty"`
	// Start date (e.g., 'Jan 2020', '2020').
	StartDate *string `json:"startDate,omitempty"`
	// End date (e.g., 'Dec 2023', 'Present').
	EndDate *string `json:"endDate,omitempty"`
	// Whether currently studying here.
	IsCurrent bool `json:"isCurrent"`
	// Description or achievements.
	Description *string `json:"description,omitempty"`
	// GPA if applicable.
	Gpa *string `json:"gpa,omitempty"`
	// Display order for sorting.
	DisplayOrder int `json:"displayOrder"`
	// Source of this education entry.
	Source    ExperienceSource `json:"source"`
	CreatedAt time.Time        `json:"createdAt"`
	UpdatedAt time.Time        `json:"updatedAt"`
}

// A work experience entry in a user's profile.
type ProfileExperience struct {
	// Unique identifier for the experience.
	ID string `json:"id"`
	// Company or organization name.
	Company string `json:"company"`
	// Job title or position.
	Title string `json:"title"`
	// Location of the job.
	Location *string `json:"location,omitempty"`
	// Start date (e.g., 'Jan 2020', '2020').
	StartDate *string `json:"startDate,omitempty"`
	// End date (e.g., 'Dec 2023', 'Present').
	EndDate *string `json:"endDate,omitempty"`
	// Whether this is the current job.
	IsCurrent bool `json:"isCurrent"`
	// Job description or responsibilities.
	Description *string `json:"description,omitempty"`
	// Key achievements or highlights (bullet points).
	Highlights []string `json:"highlights"`
	// Display order for sorting.
	DisplayOrder int `json:"displayOrder"`
	// Source of this experience entry.
	Source    ExperienceSource `json:"source"`
	CreatedAt time.Time        `json:"createdAt"`
	UpdatedAt time.Time        `json:"updatedAt"`
}

// A skill entry in a user's profile.
type ProfileSkill struct {
	// Unique identifier for the skill.
	ID string `json:"id"`
	// Skill name as displayed.
	Name string `json:"name"`
	// Normalized skill name for deduplication.
	NormalizedName string `json:"normalizedName"`
	// Skill category.
	Category domain.SkillCategory `json:"category"`
	// Display order for sorting.
	DisplayOrder int `json:"displayOrder"`
	// Source of this skill entry.
	Source    ExperienceSource `json:"source"`
	CreatedAt time.Time        `json:"createdAt"`
	UpdatedAt time.Time        `json:"updatedAt"`
}

type Query struct {
}

// A reference letter with extracted data.
type ReferenceLetter struct {
	ID           string     `json:"id"`
	Title        *string    `json:"title,omitempty"`
	AuthorName   *string    `json:"authorName,omitempty"`
	AuthorTitle  *string    `json:"authorTitle,omitempty"`
	Organization *string    `json:"organization,omitempty"`
	DateWritten  *time.Time `json:"dateWritten,omitempty"`
	RawText      *string    `json:"rawText,omitempty"`
	// Structured data extracted from the letter by LLM processing.
	ExtractedData *ExtractedLetterData  `json:"extractedData,omitempty"`
	Status        ReferenceLetterStatus `json:"status"`
	CreatedAt     time.Time             `json:"createdAt"`
	UpdatedAt     time.Time             `json:"updatedAt"`
	User          *User                 `json:"user"`
	File          *File                 `json:"file,omitempty"`
}

// An uploaded resume with extracted profile data.
type Resume struct {
	ID string `json:"id"`
	// Processing status of the resume.
	Status ResumeStatus `json:"status"`
	// Structured data extracted from the resume by LLM processing.
	ExtractedData *ResumeExtractedData `json:"extractedData,omitempty"`
	// Error message if processing failed.
	ErrorMessage *string   `json:"errorMessage,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
	User         *User     `json:"user"`
	File         *File     `json:"file"`
}

// Structured data extracted from a resume.
// Education and work experience are materialized into profile tables
// and exposed via ProfileEducation/ProfileExperience types.
type ResumeExtractedData struct {
	// Full name of the candidate.
	Name string `json:"name"`
	// Email address.
	Email *string `json:"email,omitempty"`
	// Phone number.
	Phone *string `json:"phone,omitempty"`
	// Location (city, state, country).
	Location *string `json:"location,omitempty"`
	// Professional summary or objective.
	Summary *string `json:"summary,omitempty"`
	// When the extraction was performed.
	ExtractedAt time.Time `json:"extractedAt"`
	// Overall confidence score (0.0 to 1.0).
	Confidence float64 `json:"confidence"`
}

// Result of a successful skill operation.
type SkillResult struct {
	// The created or updated skill.
	Skill *ProfileSkill `json:"skill"`
}

func (SkillResult) IsSkillResponse() {}

// Error returned when skill validation fails.
type SkillValidationError struct {
	// Error message describing the validation failure.
	Message string `json:"message"`
	// The field that failed validation.
	Field *string `json:"field,omitempty"`
}

func (SkillValidationError) IsSkillResponse() {}

// Input for updating an existing education entry.
type UpdateEducationInput struct {
	// Institution name.
	Institution *string `json:"institution,omitempty"`
	// Degree or certification.
	Degree *string `json:"degree,omitempty"`
	// Field of study.
	Field *string `json:"field,omitempty"`
	// Start date (e.g., 'Jan 2020', '2020').
	StartDate *string `json:"startDate,omitempty"`
	// End date (e.g., 'Dec 2023', 'Present').
	EndDate *string `json:"endDate,omitempty"`
	// Whether currently studying here.
	IsCurrent *bool `json:"isCurrent,omitempty"`
	// Description or achievements.
	Description *string `json:"description,omitempty"`
	// GPA if applicable.
	Gpa *string `json:"gpa,omitempty"`
}

// Input for updating an existing work experience.
type UpdateExperienceInput struct {
	// Company or organization name.
	Company *string `json:"company,omitempty"`
	// Job title or position.
	Title *string `json:"title,omitempty"`
	// Location of the job.
	Location *string `json:"location,omitempty"`
	// Start date (e.g., 'Jan 2020', '2020').
	StartDate *string `json:"startDate,omitempty"`
	// End date (e.g., 'Dec 2023', 'Present').
	EndDate *string `json:"endDate,omitempty"`
	// Whether this is the current job.
	IsCurrent *bool `json:"isCurrent,omitempty"`
	// Job description or responsibilities.
	Description *string `json:"description,omitempty"`
	// Key achievements or highlights (bullet points).
	Highlights []string `json:"highlights,omitempty"`
}

// Input for updating an existing skill.
type UpdateSkillInput struct {
	// Skill name.
	Name *string `json:"name,omitempty"`
	// Skill category.
	Category *domain.SkillCategory `json:"category,omitempty"`
}

// Result of a file upload operation.
type UploadFileResult struct {
	// The uploaded file metadata.
	File *File `json:"file"`
	// The reference letter created for processing.
	ReferenceLetter *ReferenceLetter `json:"referenceLetter"`
}

func (UploadFileResult) IsUploadFileResponse() {}

// Result of a resume upload operation.
type UploadResumeResult struct {
	// The uploaded file metadata.
	File *File `json:"file"`
	// The resume created for processing.
	Resume *Resume `json:"resume"`
}

func (UploadResumeResult) IsUploadResumeResponse() {}

// A user account in the system.
type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Name      *string   `json:"name,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// Source of a profile experience entry.
type ExperienceSource string

const (
	// Manually entered by user.
	ExperienceSourceManual ExperienceSource = "MANUAL"
	// Extracted from an uploaded resume.
	ExperienceSourceResumeExtracted ExperienceSource = "RESUME_EXTRACTED"
)

var AllExperienceSource = []ExperienceSource{
	ExperienceSourceManual,
	ExperienceSourceResumeExtracted,
}

func (e ExperienceSource) IsValid() bool {
	switch e {
	case ExperienceSourceManual, ExperienceSourceResumeExtracted:
		return true
	}
	return false
}

func (e ExperienceSource) String() string {
	return string(e)
}

func (e *ExperienceSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExperienceSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExperienceSource", str)
	}
	return nil
}

func (e ExperienceSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExperienceSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExperienceSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Processing status of a reference letter.
type ReferenceLetterStatus string

const (
	ReferenceLetterStatusPending    ReferenceLetterStatus = "PENDING"
	ReferenceLetterStatusProcessing ReferenceLetterStatus = "PROCESSING"
	ReferenceLetterStatusCompleted  ReferenceLetterStatus = "COMPLETED"
	ReferenceLetterStatusFailed     ReferenceLetterStatus = "FAILED"
)

var AllReferenceLetterStatus = []ReferenceLetterStatus{
	ReferenceLetterStatusPending,
	ReferenceLetterStatusProcessing,
	ReferenceLetterStatusCompleted,
	ReferenceLetterStatusFailed,
}

func (e ReferenceLetterStatus) IsValid() bool {
	switch e {
	case ReferenceLetterStatusPending, ReferenceLetterStatusProcessing, ReferenceLetterStatusCompleted, ReferenceLetterStatusFailed:
		return true
	}
	return false
}

func (e ReferenceLetterStatus) String() string {
	return string(e)
}

func (e *ReferenceLetterStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReferenceLetterStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReferenceLetterStatus", str)
	}
	return nil
}

func (e ReferenceLetterStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReferenceLetterStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReferenceLetterStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Processing status of a resume.
type ResumeStatus string

const (
	ResumeStatusPending    ResumeStatus = "PENDING"
	ResumeStatusProcessing ResumeStatus = "PROCESSING"
	ResumeStatusCompleted  ResumeStatus = "COMPLETED"
	ResumeStatusFailed     ResumeStatus = "FAILED"
)

var AllResumeStatus = []ResumeStatus{
	ResumeStatusPending,
	ResumeStatusProcessing,
	ResumeStatusCompleted,
	ResumeStatusFailed,
}

func (e ResumeStatus) IsValid() bool {
	switch e {
	case ResumeStatusPending, ResumeStatusProcessing, ResumeStatusCompleted, ResumeStatusFailed:
		return true
	}
	return false
}

func (e ResumeStatus) String() string {
	return string(e)
}

func (e *ResumeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ResumeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ResumeStatus", str)
	}
	return nil
}

func (e ResumeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ResumeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ResumeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
